concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-original-gitlab"
  url = "https://gitlab.com/"
  id = 24130311
  token = "2DKs3kix3vLzc6jDjCoT"
  token_obtained_at = 2023-06-07T19:02:15Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "public.localhost/utile/docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0

[[runners]]
  name = "docker-gitlab-example-com"
  url = "http://gitlab.example.com/"
  id = 7
  token = "akGsLdvioyuy7hjSTKnD"
  token_obtained_at = 2023-06-08T18:10:13Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  clone_url = "http://gitlab.example.com/"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    network_mode = "host"
    tls_verify = false
    image = "public.localhost/utile/docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock","/cache"]
    shm_size = 0
