version: '3.9'

services:
  traefik-service:
    image: traefik:v2.4.8
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/acme
      - ./traefik:/traefik
    networks:
      - default
    command:
      - "--log.level=INFO"
      - "--log.filepath=/traefik.log"
      - "--log.format=json"

      - "--api=true"
      - "--ping=true"
      - "--accesslog=true"
      - "--accesslog.bufferingsize=100"
      - "--api.insecure=true"

      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=dccn_net"

      - "--entrypoints.ssh.address=:22"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--providers.file.filename=/traefik/config.yml"

      #- "--entrypoints.web.address=:80"
      #- "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      #- "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      #- "--entrypoints.websecure.address=:443"   
      
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dccn_net"

      - "traefik.http.routers.traefik-http.entrypoints=web"
      - "traefik.http.routers.traefik-http.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik-http.middlewares=traefik-redirect-http"
      - "traefik.http.middlewares.traefik-redirect-http.redirectscheme.scheme=https"
      
      - "traefik.http.routers.traefik-https.entrypoints=websecure"
      - "traefik.http.routers.traefik-https.rule=Host(`traefik.localhost`)"

      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.routers.traefik-https.tls.options=default"
      - "traefik.http.routers.traefik-https.tls.certresolver=mycert"

      # traefik.http.middlewares.basic-auth-global.basicauth.users: <username>:<encoded-password>
      - "traefik.http.middlewares.basic-auth-global.basicauth.users=user:$$apr1$$iBy9InM6$$vxJGTqKth.ww3Ct8WVf2e1"
      - "traefik.http.routers.traefik-https.middlewares=basic-auth-global"
      
      - "traefik.http.services.traefik-https.loadbalancer.server.port=8080"

  gitlab-service:
    image: 'gitlab/gitlab-ee:latest'
    restart: unless-stopped
    container_name: gitlab
    networks:
      - default
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: 512m
    mem_limit: 5g
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dccn_net"

      - "traefik.http.routers.gitlab-http.entrypoints=web"
      - "traefik.http.routers.gitlab-http.rule=Host(`gitlab.example.com`)"

      - "traefik.http.routers.gitlab-http.service=gitlab-http"
      - "traefik.http.services.gitlab-http.loadbalancer.server.port=80"

      - "traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitlab-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-svc"
      - "traefik.tcp.services.gitlab-ssh-svc.loadbalancer.server.port=22"

    environment:
      GITLAB_OMNIBUS_CONFIG: |

        # Server Configuration
        external_url 'http://gitlab.example.com'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['gitlab_shell_ssh_port'] = 22

  nexus-service:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    volumes:
      - nexus_data:/nexus-data
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dccn_net"

      # UI nexus
      - "traefik.http.routers.nexus-http.entrypoints=web"
      - "traefik.http.routers.nexus-http.rule=Host(`registry.localhost`)"

      - "traefik.http.routers.nexus-https.entrypoints=websecure"
      - "traefik.http.routers.nexus-http.service=nexus-https"
      - "traefik.http.routers.nexus-https.rule=Host(`registry.localhost`)"
      
      - "traefik.http.routers.nexus-https.tls=true"
      - "traefik.http.routers.nexus-https.tls.options=default"
      - "traefik.http.routers.nexus-https.tls.certresolver=mycert"

      - "traefik.http.routers.nexus-https.service=nexus-https"
      - "traefik.http.services.nexus-https.loadbalancer.server.port=8081"

      # Docker proxy
      - "traefik.http.routers.docker-http.entrypoints=web"
      - "traefik.http.routers.docker-http.rule=Host(`docker.localhost`)"
      
      - "traefik.http.routers.docker-https.entrypoints=websecure"
      - "traefik.http.routers.docker-http.service=docker-https"
      - "traefik.http.routers.docker-https.rule=Host(`docker.localhost`)"

      - "traefik.http.routers.docker-https.tls=true"
      - "traefik.http.routers.docker-https.tls.options=default"
      - "traefik.http.routers.docker-https.tls.certresolver=mycert"

      - "traefik.http.routers.docker-https.service=docker-https"
      - "traefik.http.services.docker-https.loadbalancer.server.port=8082"

      # Docker private 
      - "traefik.http.routers.private-http.entrypoints=web"
      - "traefik.http.routers.private-http.rule=Host(`private.localhost`)"

      - "traefik.http.routers.private-https.entrypoints=websecure"
      - "traefik.http.routers.private-http.service=private-https"
      - "traefik.http.routers.private-https.rule=Host(`private.localhost`)"

      - "traefik.http.routers.private-https.tls=true"
      - "traefik.http.routers.private-https.tls.options=default"
      - "traefik.http.routers.private-https.tls.certresolver=mycert"

      - "traefik.http.routers.private-https.service=private-https"
      - "traefik.http.services.private-https.loadbalancer.server.port=8083"

      # Docker public
      - "traefik.http.routers.public-http.entrypoints=web"
      - "traefik.http.routers.public-http.rule=Host(`public.localhost`)"

      - "traefik.http.routers.public-https.entrypoints=websecure"
      - "traefik.http.routers.public-http.service=public-https"
      - "traefik.http.routers.public-https.rule=Host(`public.localhost`)"

      - "traefik.http.routers.public-https.tls=true"
      - "traefik.http.routers.public-https.tls.options=default"
      - "traefik.http.routers.public-https.tls.certresolver=mycert"

      - "traefik.http.routers.public-https.service=public-https"
      - "traefik.http.services.public-https.loadbalancer.server.port=8084"

volumes:
  traefik-acme:
  nexus_data:
  gitlab-config:
  gitlab-data:
  gitlab-logs:

networks:
  default:
    name: dccn_net